# Generated by Django 3.1 on 2020-10-14 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vet', models.BooleanField(default=False)),
                ('is_nurse', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fortnight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('current', models.BooleanField(default=False, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFortnight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('fortnight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.fortnight')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('normal_qh', models.PositiveIntegerField(default=32)),
                ('worked_qh', models.PositiveIntegerField(default=0)),
                ('sick_qh', models.PositiveIntegerField(default=0)),
                ('leave_qh', models.PositiveIntegerField(default=0)),
                ('publich_qh', models.PositiveIntegerField(default=0)),
                ('study_qh', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(default='')),
                ('fortnight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.fortnight')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.employee')),
            ],
        ),
    ]
