# Generated by Django 3.1 on 2020-08-16 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('normal_quarterhours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarterhours', models.IntegerField()),
                ('worktype', models.CharField(choices=[('N', 'Normal'), ('S', 'Sick'), ('L', 'Leave'), ('P', 'Public Holiday'), ('Z', 'Study Leave')], max_length=1)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.day')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.person')),
            ],
        ),
    ]
