# Generated by Django 3.1 on 2020-10-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortnight',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
