# Generated by Django 3.1 on 2020-08-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='worktype',
            field=models.CharField(choices=[('N', 'Working'), ('S', 'Sick Leave'), ('L', 'Paid Leave'), ('P', 'Public Holiday'), ('Z', 'Study Leave')], default='N', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='interval',
            unique_together={('day', 'worktype')},
        ),
    ]
