# Generated by Django 3.1 on 2020-08-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interval',
            name='person',
        ),
        migrations.AddField(
            model_name='day',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.person'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='worktype',
            field=models.CharField(choices=[('N', 'Normal'), ('S', 'Sick Leave'), ('L', 'Paid Leave'), ('P', 'Public Holiday'), ('Z', 'Sudy Leave')], default='N', max_length=1),
        ),
    ]
