# Generated by Django 3.1 on 2020-09-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_squashed_0004_auto_20200916_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fortnight',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
