# Generated by Django 3.1 on 2020-09-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_unique_intervals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='normal_quarterhours',
        ),
        migrations.AddField(
            model_name='day',
            name='leave_qh',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='normal_qh',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='day',
            name='publich_qh',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='sick_qh',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='study_qh',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='worked_qh',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Interval',
        ),
    ]
