# Generated by Django 3.1 on 2020-09-30 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0002_auto_20200930_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='fortnight',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vet', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='day',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.employee'),
        ),
    ]
