# Generated by Django 3.1 on 2020-09-16 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0003_auto_20200902_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='normal_qh',
            field=models.PositiveIntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='day',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
