# Generated by Django 3.1 on 2020-08-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_auto_20200816_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fortnight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='interval',
            name='worktype',
            field=models.CharField(choices=[('N', 'Working'), ('S', 'Sick Leave'), ('L', 'Paid Leave'), ('P', 'Public Holiday'), ('Z', 'Sudy Leave')], default='N', max_length=1),
        ),
    ]
