# Generated by Django 3.1 on 2020-10-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20200930_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortnight',
            name='notes',
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_nurse',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmployeeFortnight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.employee')),
            ],
        ),
    ]
