# Generated by Django 3.1 on 2020-08-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20200819_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortnight',
            name='current',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
